site_name: PDF Extraction API
site_description: A Python-based API service for extracting text, images, and metadata from PDF files
site_author: Aman Kumar
site_url: https://amankumar006.github.io/PDF-Extraction-API/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: Amankumar006/PDF-Extraction-API
repo_url: https://github.com/Amankumar006/PDF-Extraction-API

nav:
  - Home: index.md
  - Features: features.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - API Reference: api.md
  - Deployment: deployment.md
  - Contributing: contributing.md
  - Changelog: changelog.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_category_heading: true 